services:
  # 后端 API 服务
  - type: web
    name: myskillstore-api
    env: docker
    plan: free
    dockerFilePath: api.Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: myskillstore-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # 前端 Web 服务
  - type: web
    name: myskillstore-web
    env: docker
    plan: free
    healthCheckPath: /
    dockerFilePath: web.Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_API_URL
        value: https://myskillstore-api.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://myskillstore-api.onrender.com

databases:
  - name: myskillstore-db
    plan: free
    databaseName: myskillstore
    user: admin
