services:
  # 后端 API 服务
  - type: web
    name: my-skill-api-kane
    env: docker
    plan: free
    dockerFilePath: api.Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: myskillshop-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # 前端 Web 服务
  - type: web
    name: myskillshop-web
    env: docker
    plan: free
    healthCheckPath: /
    dockerFilePath: web.Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://my-skill-shop.onrender.com

databases:
  - name: myskillshop-db
    plan: free
    databaseName: myskillshop
    user: admin
